spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
    contexts: "!nocontext"
#    feature-flags: feature-3,feature-4,feature-6,feature-7

feature-flags: feature-flag-3,feature-flag-4,feature-flag-6,feature-flag-7

unleash:
  appName: "default"
  clientSecret: "default:development.unleash-insecure-api-token"
  apiUrl: "http://localhost:4242/api/"
  instanceId: "1"
  adminToken: "*:*.b807572466b8d7cf5c8edaf3af487092296cbeb721f3185c3ecbf44e"

