name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print current directory
        run: |
          pwd
          ls -al
      - name: Build and Deploy with Docker Compose
        run: |
          docker-compose -f feature-toggle-concept-poc/docker-compose.yaml up -d --build
