name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Deploy with Docker Compose
        run: |
          cd feature-toggle-concept-poc
          docker-compose up -d --build
